language: objective-c
xcode_workspace: Example/TraceLog.xcworkspace
xcode_scheme: TraceLog-Example
osx_image: xcode7.3

before_install:
    - brew install xctool
    - gem install cocoapods --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent
    
script:
  - pod lib lint
  
  - xctool -workspace Example/TraceLog.xcworkspace -scheme TraceLog-iOS-Example -sdk iphonesimulator test
  - xctool -workspace Example/TraceLog.xcworkspace -scheme TraceLog-OSX-Example -sdk macosx test

after_success:
  - bash <(curl -s https://codecov.io/bash)
